%% Import data from text file.
% Script for importing data from the following text file:
%
%    /home/rafael/Dropbox/Backup
%    Documentos/Mestrado/Tese/Dev/Modelagem/Circuito
%    passivo/Fx:dx=0,6-1,2:dz=0.txt.csv
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2014/03/04 19:43:36

%% Initialize variables.
filename = '/home/rafael/Dropbox/Backup Documentos/Mestrado/Tese/Dev/Modelagem/Circuito passivo/Fx:dx=0,6-1,2:dz=0.txt.csv';
delimiter = ',';
startRow = 6;

%% Format string for each line of text:
%   column1: double (%f)
%	column2: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%f%*s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'HeaderLines' ,startRow-1, 'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Create output variable
dataArray = cellfun(@(x) num2cell(x), dataArray, 'UniformOutput', false);
Comsol_Fx_dx_dy0 = [dataArray{1:end-1}];
%% Clear temporary variables
clearvars filename delimiter startRow formatSpec fileID dataArray ans;